database:
  image: "docker.io/sameersbn/postgresql:9.4-4"
  environment:
    DB_USER: zulip
    DB_PASS: zulip
    DB_NAME: zulip
  volumes:
    - "/opt/docker/postgresql/data:/var/lib/postgresql:rw"
memcache:
  image: "docker.io/sameersbn/memcached:latest"
  restart: always
rabbitmq:
  image: "docker.io/rabbitmq:3.5.5"
  hostname: zulip-rabbit
camo:
  image: "docker.io/galexrt/camo:latest"
redis:
  image: "docker.io/sameersbn/redis:latest"
  volumes:
    - "/opt/docker/redis:/var/lib/redis:rw"
zulip:
  image: "docker.io/galexrt/zulip:latest"
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
    - memcache
    - rabbitmq
    - camo
    - redis
  environment:
    DB_HOST: "database"
    ZULIP_USER_EMAIL: "example@example.com"
    ZULIP_SECRETS_email_password: "12345"
  volumes:
    - "/opt/docker/zulip:/data:rw"
