database:
  image: "quay.io/sameersbn/postgresql:9.4-5"
  environment:
    DB_NAME: zulip
    DB_USER: zulip
    DB_PASS: zulip
  volumes:
    - "/opt/docker/postgresql/data:/var/lib/postgresql:rw"
    - "/opt/docker/postgresql/dicts/en_us.dict:/usr/share/postgresql/9.4/tsearch_data/en_us.dict"
    - "/opt/docker/postgresql/dicts/en_us.affix:/usr/share/postgresql/9.4/tsearch_data/en_us.affix"
    - "/opt/docker/postgresql/dicts/zulip_english.stop:/usr/share/postgresql/9.4/tsearch_data/zulip_english.stop"
memcache:
  image: "quay.io/sameersbn/memcached:latest"
  restart: always
rabbitmq:
  image: "docker.io/rabbitmq:3.5.5"
  hostname: zulip-rabbit
  environment:
      RABBITMQ_DEFAULT_USER: "zulip"
      RABBITMQ_DEFAULT_PASS: "zulip"
camo:
  image: "quay.io/galexrt/camo:latest"
redis:
  image: "quay.io/sameersbn/redis:latest"
  volumes:
    - "/opt/docker/redis:/var/lib/redis:rw"
zulip:
  image: "quay.io/galexrt/zulip:latest"
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
    - memcache
    - rabbitmq
    - camo
    - redis
  environment:
    DB_HOST: "database"
    MEMCACHED_HOST: "memcache"
    REDIS_HOST: "redis"
    RABBITMQ_HOST: "rabbitmq"
    ZULIP_USER_EMAIL: "example@example.com"
    ZULIP_SECRETS_email_password: "12345"
    ZULIP_SECRETS_rabbitmq_password: "zulip"
    ZULIP_SETTINGS_EXTERNAL_HOST: "localhost"
    ZULIP_SETTINGS_ZULIP_ADMINISTRATOR: "admin@example.com"
    ZULIP_SETTINGS_ADMIN_DOMAIN: "zerbytes.net"
    ZULIP_SETTINGS_NOREPLY_EMAIL_ADDRESS: "noreply@example.com"
    ZULIP_SETTINGS_DEFAULT_FROM_EMAIL: "Zulip <noreply@example.com>"
    ZULIP_SETTINGS_EMAIL_HOST: "smtp.example.com"
    ZULIP_SETTINGS_EMAIL_HOST_USER: "noreply@example.com"
  volumes:
    - "/opt/docker/zulip:/data:rw"
