database:
  image: "docker.io/sameersbn/postgresql:9.4-4"
  environment:
    DB_USER: zulip
    DB_PASS: zulip
    DB_NAME: zulip
  volumes:
    - "/opt/postgresql/data:/var/lib/postgresql:rw"
memcache:
  image: "sameersbn/memcached:latest"
  restart: always
rabbitmq:
  image: "rabbitmq:3.5.5"
  hostname: zulip-rabbit
camo:
  image: "docker.io/galexrt/docker-camo:latest"
zulip:
  image: "docker.io/galexrt/zulip:latest"
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
    - memcache
    - rabbitmq
    - camo
    - redis
redis:
  image: "sameersbn/redis:latest"
  volumes:
    - "/opt/docker/redis:/var/lib/redis:rw"
