database:
  image: "docker.io/postgresql:9.3"
  environment:
    POSTGRES_USER: zulip
    POSTGRES_PASSWORD: zulip
  volumes:
    - "/opt/docker/postgresql/data:/var/lib/postgresql:rw"
memcache:
  image: "docker.io/sameersbn/memcached:latest"
  restart: always
rabbitmq:
  image: "docker.io/rabbitmq:3.5.5"
  hostname: zulip-rabbit
camo:
  image: "docker.io/galexrt/camo:latest"
redis:
  image: "docker.io/sameersbn/redis:latest"
  volumes:
    - "/opt/docker/redis:/var/lib/redis:rw"
zulip:
  image: "docker.io/galexrt/zulip:latest"
  ports:
    - "80:80"
    - "443:443"
  links:
    - database
    - memcache
    - rabbitmq
    - camo
    - redis
  environment:
    DB_HOST: "database"
    ZULIP_USER_EMAIL: "example@example.com"
    ZULIP_SECRETS_email_password: "12345"
    ZULIP_SETTINGS_ZULIP_ADMINISTRATOR: "admin@example.com"
    ZULIP_SETTINGS_ADMIN_DOMAIN: "zerbytes.net"
    ZULIP_SETTINGS_NOREPLY_EMAIL_ADDRESS: "noreply@example.com"
    ZULIP_SETTINGS_DEFAULT_FROM_EMAIL: "Zulip <noreply@example.com>"
    ZULIP_SETTINGS_EMAIL_HOST: "smtp.example.com"
    ZULIP_SETTINGS_EMAIL_HOST_USER: "noreply@example.com"
  volumes:
    - "/opt/docker/zulip:/data:rw"
